sitemusican/main/urls.py
from django.conf.urls.static import static
from django.urls import path, include, re_path
from . import views
from django.contrib import admin
from sait import settings

from rest_framework import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

'''class MyCustomRouter(routers.SimpleRouter):
    routes = [
        routers.Route(url=r'^{prefix}$',
                      mapping={'get': 'list'},
                      name='{basename}-list',
                      detail=False,
                      initkwargs={'suffix': 'List'}),
        routers.Route(url=r'^{prefix}/{lookup}$',
                      mapping={'get': 'retrieve'},
                      name='{basename}-detail',
                      detail=True,
                      initkwargs={'suffix': 'Detail'})
    ]


router = MyCustomRouter()
router.register(r'musician', views.MusicianViewSet, basename="musician")
print(router.urls)'''

urlpatterns = [
    path('', views.index, name='home'),
    path('post/', views.allposts, name='allposts'),
    path('post/<slug:post_slug>/', views.show_post, name='post'),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('post/<slug:post_slug>/', views.show_post, name='post'),
    path('api/v1/musician/', views.MusicianAPIList.as_view()),
    path('api/v1/musician/<int:pk>/', views.MusicianAPIUpdate.as_view()),
    path('api/v1/musiciandelete/<int:pk>/', views.MusicianAPIDestroy.as_view()),
    path('api/v1/auth/', include('djoser.urls')),
    path(r'^auth/', include('djoser.urls.authtoken')),
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('category/<slug:cat_slug>/', views.show_category, name='category'),
    path('tag/<slug:tag_slug>/', views.show_tag_postlist, name='tag'),
    path('addpage/', views.addpage, name='addpage'),
    path('feedback/', views.feedback, name='feedback')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Таблицы пользователь и музыкантов"

sitemusican/sait/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace="users"))
]

sitemusican/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
]

sitemusican/main/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

def translit_to_eng(s: str) -> str:
    d = {'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd',
         'е': 'e', 'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i', 'к': 'k',
         'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r',
         'с': 's', 'т': 't', 'у': 'u', 'ф': 'f', 'х': 'h', 'ц': 'c', 'ч': 'ch',
         'ш': 'sh', 'щ': 'shch', 'ь': '', 'ы': 'y', 'ъ': '', 'э': 'r', 'ю': 'yu', 'я': 'ya'}

    return "".join(map(lambda x: d[x] if d.get(x, False) else x, s.lower()))


class Task(models.Model):

    title = models.CharField('Название', max_length=50)
    task = models.TextField('Описание')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'


class Musician(models.Model):
    class Status(models.IntegerChoices):
        DRAFT = 0, 'Черновик'
        PUBLISHED = 1, 'Опубликовано'


    title = models.CharField(max_length=255, verbose_name="Заголовок")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="Slug")
    content = models.TextField(blank=True, verbose_name="Текст статьи")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Время изменения")
    is_published = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)),
                                       default=Status.DRAFT, verbose_name="Статус")
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default=None, blank=True, null=True, verbose_name='Фото')
    cat = models.ForeignKey(
        'Category',
        on_delete=models.PROTECT,
        related_name='posts',
        verbose_name="Категории")
    tags = models.ManyToManyField('TagPost', blank=True, related_name='tags', verbose_name="Теги")
    alive = models.OneToOneField(
        'Alive',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='alive',
        verbose_name="Место рождения")
    user = models.ForeignKey(
        User,
        verbose_name='Пользователь',
        on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Известные музыканты"
        verbose_name_plural = "Известные музыканты"
        ordering = ['-time_create']
        indexes = [
            models.Index(fields=['-time_create'])
        ]

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(translit_to_eng(self.slug))
        super().save(*args, **kwargs)


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class TagPost(models.Model):
    tag = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    def __str__(self):
        return self.tag


class Alive(models.Model):
    place_of_birth = models.CharField(max_length=100)
    age = models.IntegerField(null=True)
    pl_country = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.place_of_birth

sitemusican/main/forms.py
from django import forms
from .models import Category, Alive


class AddPostForm(forms.Form):
    title = forms.CharField(max_length=255, label="Заголовок", widget=forms.TextInput(attrs={'class': 'form-input'}))
    slug = forms.SlugField(max_length=255, label="URL")
    content = forms.CharField(widget=forms.Textarea(attrs={'cols': 50, 'rows': 5}), required=False, label="Контент")
    is_published = forms.BooleanField(required=False, initial=True, label="Статус")
    cat = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label="Категория не выбрана", label="Категории")

sitemusican/main/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.http import JsonResponse
from rest_framework import generics, viewsets, mixins
from rest_framework.viewsets import GenericViewSet
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAdminUser, IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from rest_framework.pagination import PageNumberPagination

from .forms import AddPostForm
from .permissions import IsAdminOrReadOnly, IsOwnerOrReadOnly
from .models import Musician, Category, TagPost
from .serializers import MusicianSerializer


class MusicianAPIListPagination(PageNumberPagination):
    page_size = 3
    page_size_query_param = 'page_size'
    max_page_size = 10000


'''class MusicianViewSet(
                      mixins.CreateModelMixin,
                      mixins.RetrieveModelMixin,
                      mixins.UpdateModelMixin,
                      mixins.DestroyModelMixin,
                      mixins.ListModelMixin,
                      GenericViewSet
):
    #queryset = Musician.objects.all()
    serializer_class = MusicianSerializer

    def get_queryset(self):
        pk = self.kwargs.get("pk")

        if not pk:
            return Musician.objects.all()[:3]

        return Musician.objects.filter(pk=pk)

    @action(methods=['get'], detail=True)
    def category(self, request, pk=None):
        cats = Category.objects.get(pk=pk)
        return Response({'cats': cats.name})'''


class MusicianAPIList(generics.ListCreateAPIView):
    queryset = Musician.objects.all()
    serializer_class = MusicianSerializer
    permission_classes = (IsAuthenticatedOrReadOnly, )
    pagination_class = MusicianAPIListPagination


class MusicianAPIUpdate(generics.RetrieveUpdateAPIView):
    queryset = Musician.objects.all()
    serializer_class = MusicianSerializer
    permission_classes = (IsAuthenticated, )
    # authentication_classes = (TokenAuthentication, )


class MusicianAPIDestroy(generics.RetrieveDestroyAPIView):
    queryset = Musician.objects.all()
    serializer_class = MusicianSerializer
    permission_classes = (IsAdminOrReadOnly, )


# class MusicianAPIView(generics.ListAPIView):
#    queryset = Musician.objects.all()
#    serializer_class = MusicianSerializer


def index(request):
    posts = Musician.objects.all()
    data = {
        'posts': posts,
    }

    return render(request, 'main/index.html', data)

def feedback(request):
    posts = Musician.objects.all()
    data = {
        'posts': posts,
    }
    return render(request, 'main/feedback.html', data)

@login_required
def allposts(request):
    all_posts = Musician.objects.all()
    paginator = Paginator(all_posts, 3)  # Показывать по 3 поста на странице
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    data = {
        'posts': page_obj.object_list,  # Отображаем текущие посты
        'page_obj': page_obj,          # Объект пагинации
        'title': 'Все посты',
        'cat_selected': None
    }

    return render(request, 'main/allposts.html', data)


def show_post(request, post_slug):
    post = get_object_or_404(Musician, slug=post_slug)

    data = {
        'title': post.title,
        'post': post,
        'cat_selected': 1,
    }

    return render(request, 'main/post.html', data)


def show_category(request, cat_slug):
    category = get_object_or_404(Category, slug=cat_slug)
    posts = Musician.objects.filter(cat_id=category.pk)

    paginator = Paginator(posts, 3)  # Показываем по 3 поста на странице
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    data = {
        'title': f'Рубрика: {category.name}',
        'posts': page_obj.object_list,
        'page_obj': page_obj,
        'cat_selected': category.pk,
    }
    return render(request, 'main/allposts.html', context=data)

def show_tag_postlist(request, tag_slug):
    tag = get_object_or_404(TagPost, slug=tag_slug)
    posts = tag.tags.filter(is_published=Musician.Status.PUBLISHED)

    data = {
        'title': f"Тег: {tag.tag}",
        'posts': posts,
        'cat_selected': None,
    }

    return render(request, 'main/allposts.html', context=data)

def addpage(request):
    if request.method == 'POST':
        form = AddPostForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data)
            try:
                Musician.objects.create(**form.cleaned_data)
                return redirect('home')
            except:
                form.add_error(None, "Ошибка добавления поста")
    else:
        form = AddPostForm()

    data = {
        'title': 'Добавление статьи',
        'form': form
    }
    return render(request, 'main/addpage.html', data)

sitemusican/main/templates/main/addpage.html
{% extends 'main/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<form action="" method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Отправить</button></p>
</form>
{% endblock %}

sitemusican/main/templates/main/allposts.html
{% extends 'main/base.html' %}
{% load musican_tags %}
{% block content %}

<style>
    .content-container {
        display: flex;
        align-items: flex-start;
        gap: 20px;
    }

    .sidebar {
        width: 280px;
        background-color: #f8f9fa;
        padding: 15px;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .main-content {
        flex-grow: 1;
        display: flex;
        flex-direction: column;
        min-height: calc(100vh - 100px);
    }

    .posts {
        flex-grow: 1;
    }

    .pagination-container {
        text-align: center;
        margin-top: 20px;
        margin-bottom: 20px;
    }
</style>

<div class="content-container">
    <!-- Sidebar -->
    <div class="sidebar">
        <h4>Категории</h4>
        <hr>
        {% show_categories cat_selected %}
        <hr>
    </div>

    <!-- Main Content -->
    <div class="main-content">

        <h1>{{ title }}</h1>
        <hr>

        <!-- Список статей -->
        <div class="posts">
            <ul>
                {% for p in posts %}
                {% if p.is_published %}
                <li>
                    <h2>{{ p.title }}</h2>
                    <p>{{ p.content |truncatechars:250 }}</p>
                    <p><a href="{% url 'post' p.slug %}">Читать пост</a></p>
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                </li>
                {% endif %}
                {% endfor %}
            </ul>
            <hr>
        </div>

        <!-- Пагинация -->
        <div class="pagination-container">
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% endif %}

                    {% for p in page_obj.paginator.page_range %}
                    {% if p == page_obj.number %}
                    <li class="page-item active"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
                    {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>

{% endblock %}

sitemusican/main/templates/main/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-expand-md bg-dark sticky-top border-bottom" data-bs-theme="dark">
  <div class="container">
    <a class="navbar-brand d-md-none" href="#">
      <svg class="bi" width="24" height="24"><use xlink:href="#aperture"></use></svg>
      Aperture
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" aria-controls="offcanvas" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvas" aria-labelledby="offcanvasLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasLabel">Aperture</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav flex-grow-1 justify-content-between">
          <li class="nav-item"><a class="nav-link" href="#">
            <svg class="bi" width="24" height="24"><use xlink:href="#aperture"></use></svg>
          </a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Главная</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'allposts' %}">Статьи</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'feedback' %}">Обратнаая связь</a></li>
          {% if user.is_authenticated %}
          <li class="nav-item">{{user.name}}<a class="nav-link" href="{% url 'users:logout' %}">Выйти</a></li>
          {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Войти</a></li>
          <li class="nav-item">{{user.name}}<a class="nav-link" href="{% url 'users:register' %}">Регистрация</a></li>
          {% endif %}
          <li class="nav-item"><a class="nav-link" href="#">
            <svg class="bi" width="24" height="24"><use xlink:href="#cart"></use></svg>
          </a></li>
        </ul>
      </div>
    </div>
  </div>
</nav>
{% block content %}{% endblock %}
</body>
</html>

sitemusican/main/templates/main/books.html
{% extends 'main/base.html' %}

{% block title %}
Таблица книг
{% endblock %}

{% block content %}
    <table>
        <tr>
            <td>Название</td>
            <td>Автор</td>
        </tr>
        <tr>
            <td>The Great Gatsby</td>
            <td>F. Scott Fitzgerald</td>
        </tr>
        <tr>
            <td>To Kill a Mockingbird</td>
            <td>Harper Lee</td>
        </tr>
        <tr>
            <td>1984</td>
            <td>George Orwell</td>
        </tr>
    </table>
{% endblock %}

sitemusican/main/templates/main/feedback.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<h1 class="text-center">Обратная связь</h1>

<div class="d-flex justify-content-center align-items-center flex-column">
    <p class="text-center">Вы можете связаться с нами через социальные сети:</p>

    <div class="d-flex justify-content-center">
        <!-- VK Icon -->
        <a href="https://vk.com/got_ball" target="_blank" class="mx-2 text-decoration-none">
            <img src="{% static 'svg/icons8-vk.svg' %}" alt="VK" width="40" height="40" class="social-icon" />
        </a>

        <!-- Telegram Icon -->
        <a href="#" target="_blank" class="mx-2 text-decoration-none">
            <img src="{% static 'svg/icons8-telegram.svg' %}" alt="Telegram" width="40" height="40" class="social-icon">
        </a>

        <!-- Instagram Icon -->
        <a href="#" target="_blank" class="mx-2 text-decoration-none">
            <img src="{% static 'svg/icons8-instagram.svg' %}" alt="Instagram" width="40" height="40" class="social-icon">
        </a>

        <!-- Email Icon -->
        <a href="#" class="mx-2 text-decoration-none">
            <img src="{% static 'svg/icons8-mail.svg' %}" alt="Email" width="40" height="40" class="social-icon">
        </a>
    </div>
</div>

<style>
    .social-icon {
        transition: transform 0.3s ease, opacity 0.3s ease;
    }

    .social-icon:hover {
        transform: scale(1.2);
        opacity: 0.8;
    }

    .text-center {
        margin-top: 20px;
        font-weight: bold;
    }

    .d-flex {
        margin-top: 30px;
    }
</style>
{% endblock %}

sitemusican/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}
Моя страница
{% endblock %}

{% block content %}
    <h1>{{ title }}</h1>

<div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
    <div class="col-lg-6 px-0">
      <h1 class="display-4 fst-italic">Сайт, в котором собраны музыканты всех времен</h1>
      <p class="lead my-3">Всех времен, по мнению некого студента. Можете ознакомиться с небольшим количество статей, приведенных на нашем сайте.</p>
      <p class="lead mb-0"><a href="{% url 'allposts' %}" class="text-body-emphasis fw-bold">Перейти к статьям</a></p>
    </div>
</div>

<div class="row mb-2">
    {% for p in posts %}
    {% if forloop.first and p.is_published %}
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0">{{ p.title }}</h3>
          <div class="mb-1 text-body-secondary">{{ p.published_date }}</div>
          <p class="card-text mb-auto">{{ p.content|truncatechars:90 }}</p>
          <a href="{% url 'post' p.slug %}" class="icon-link gap-1 icon-link-hover stretched-link">
            Читать пост
            <svg class="bi"><use xlink:href="#chevron-right"></use></svg>
          </a>
        </div>
        <div class="col-auto d-none d-lg-block">
          {% if p.photo %}
          <img class="img-article-left" src="{{ p.photo.url }}" alt="Thumbnail" width="200" height="250">
          {% endif %}
        </div>
      </div>
    </div>
    {% endif %}

    {% if forloop.last and p.is_published %}
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0">{{ p.title }}</h3>
          <div class="mb-1 text-body-secondary">{{ p.published_date }}</div>
          <p class="mb-auto">{{ p.content|truncatechars:90 }}</p>
          <a href="{% url 'post' p.slug %}" class="icon-link gap-1 icon-link-hover stretched-link">
            Читать пост
            <svg class="bi"><use xlink:href="#chevron-right"></use></svg>
          </a>
        </div>
        <div class="col-auto d-none d-lg-block">
          {% if p.photo %}
          <img class="img-article-left" src="{{ p.photo.url }}" alt="Thumbnail" width="200" height="250">
          {% endif %}
        </div>
      </div>
    </div>
    {% endif %}
    {% endfor %}
</div>

<div class="container">
  <div class="col-md-8">
        <h3 class="pb-4 mb-4 fst-italic border-bottom">
          Из пожарного шланга
        </h3>

        <article class="blog-post">
          <h2 class="display-5 link-body-emphasis mb-1">Музыкальный Привет!</h2>
          <p class="blog-post-meta">Январь 10, 2025 by admin</a></p>

          <p>Этот блог посвящён внедрению в мою историю. Хочу поделиться, почему я выбрал именно музыкальную тематику для своего проекта.</p>
          <hr>
          <p>Музыка всегда занимала важное место в моей жизни. Она вдохновляет, помогает выражать эмоции и создаёт особую атмосферу. Мне захотелось объединить своё увлечение музыкой с навыками, которые я развиваю. Поэтому я решил создать музыкальный сайт — платформу, где можно прочитать стать о музыкантах, узнавать о новых исполнителях.</p>
          <h2>Немного истории</h2>
          <blockquote class="blockquote">
            <p>Меня в 14 лет выгнали с музыкальной школы.</p>
          </blockquote>
          <p>Причем не из-за оценок, а из-за моего возраста, слишком большим пошел - не успел бы закончить до 17 лет. Нужно было платить деньги за обучение, что не могли себе позволить. Да и я не хотел.</p>
          <h3>Я (был) панк!</h3>
          <p>Уйдя, я перестал играть по нотам, начам учить рифы, мне пришла гениальная мысль купить электрическую гитару. Начал отращивать патлы и ходить в старых вещах (гранж).</p>
          <ul>
            <li>SSSHHHIIITTT!!!</li>
            <li>Пасош</li>
            <li>Джизус</li>
          </ul>
          <p>Исполнители, которых я слушал до дыр.</p>
          </ol>
          <dl>
            <dt>Выступление в актовом зале школы</dt>
            <dd>Давали концерты в школе, собирались в гараже для репетиций</dd>
            <dt>Вечно недовольное лицо</dt>
            <dd>Почему-то было очень модно быть несчастливым</dd>
            <dt>Длинные волосы</dt>
            <dd>Я хотел волосы как у Курта Кобейна. Но я был похож на Гоголя нового времени.</dd>
          </dl>
        </article>

        <article class="blog-post">
          <h2 class="display-5 link-body-emphasis mb-1">Ну а что сейчас?</h2>

          <p>Время не стоит на месте, как бы сильно этого не хотелось. Смена интересов привела к тому, что пришлось состричь волосы, перестать носить старые кардиганы, джинсы, выбросить кеды, которые я запрещал маме стирать.</p>
          <blockquote>
            <p>Увлечение спортом, а главное таким, как <strong>баскетбол</strong>, поменял мою жизнь.</p>
          </blockquote>
          <p>Я начал общаться с людьми, которые имеют более высокие цели, чем всю жизнь играть по кабакам или на улице. Бегать и тренироваться мне понравилось больше, чем сидеть в грязном гараже, играть на гитарах и барабанах, попивая пиво.</p>
          <p>Настолько понравилось, что даже девушку нашел. Щас работаю, чтобы оплатить ее очередные новые кофточки...</p>
          <hr>
          <p>(Я не жалуюсь)</p>
        </article>

        <article class="blog-post">
          <h2 class="display-5 link-body-emphasis mb-1">Ну а что на сегодня?</h2>
          <p>А на сегодня ничего интересного, на гитаре я уже как 2 года не играю вообще. Раньше хоть выделял время, чтобы выучить что-нибудь, чтобы форму не терять. Забыл ноты давным давно. Но музыка все равно явлеется моим основным хобби. Анализирую тексы, слушаю новые альбомы моих любимых исполнителей. Сравниваю старые и новые работы исполнителей</p>

          <p>Слушайте музыку. Слушайте хорошую музыку, слушайте много музыки.</p>
        </article>
  </div>
</div>
{% include 'main/include/nav.html' %}

{% endblock %}

sitemusican/main/templates/main/list_categories.html
{% for cat in cats %}
{% if cat.id == cat_selected %}

<div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary" style="width: 28px; height: 25; ">
        <ul class="nav nav-pills flex-column mb-auto">
            <li>
                <a href="{% url 'category' cat.slug %}" class="nav-link link-body-emphasis">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="{{ cat.get_absolute_url }}"></use></svg>
                    {{cat.name}}
                </a>
            </li>
        </ul>
</div>
{% else %}

<div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary" style="width: 28px; height: 250; ">
        <ul class="nav nav-pills flex-column mb-auto">
            <li>
                <a href="{% url 'category' cat.slug %}" class="nav-link link-body-emphasis">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="{{ cat.get_absolute_url }}"></use></svg>
                    {{cat.name}}
                </a>
            </li>
        </ul>
</div>
{% endif %}
{% endfor %}

sitemusican/main/templates/main/list_tags.html
{% if tags %}
    <ul class="tags-list">
        {% for t in tags %}
        <li><a href="{{t.get_absolute_url}}">{{t.tag}}</a></li>
        {% endfor %}
    </ul>
{% endif %}

sitemusican/main/templates/main/post.html
{% extends 'main/base.html' %}
{% load musican_tags %}
{% block content %}

<div class="d-flex">
    <!-- Sidebar -->
    <div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary" style="width: 280px; margin-bottom: 5px;">
        <a class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <svg class="bi pe-none me-2" width="40" height="32"></svg>
            <span class="fs-4">Категории</span>
        </a>
        <hr>
        {% show_categories cat_selected %}
        <hr>
    </div>

    <!-- Content Section -->
    <div class="flex-grow-1 p-4">
        <h1>{{ post.title }}</h1>
        <div class="d-flex align-items-start">
            {% if post.photo %}
            <img src="{{ post.photo.url }}" alt="Изображение статьи" class="img-fluid img-thumbnail me-3" style="width: 300px; height: auto; object-fit: cover;">
            {% endif %}
            <p class="lead">{{ post.content }}</p>
        </div>
    </div>
</div>

{% endblock %}